- index.html
- news/2015-01-08-oer-a11y-sprint.html
- news/index.html
> FLOE-268: Updating news to include link to A11y Sprint site.

- accessibilitySprint2015.html
- css/sprint.css
- added resources section
- added agenda nav link to mobile layout.
> FLOE-268: Added Resources section

- index.html
Not to be deployed to the live site until the ILDH updates are complete.
> FLOE-286: Adding a link to the accessible standardized testing info in ILDH

- index.html
@michelled, could you have a look at the text around these links?
> FLOE-290: Add links to sonification work and TTS component.

- css/style.css
- index.html
- news/2014-04-21-metadata-search.html
- news/2014-09-30-lumen-learning.html
- news/2015-01-08-oer-a11y-sprint.html
- news/index.html
- prefsEditors.html
- security.html
@jobara, @michelled has reviewed the text for this pull request. Would be able to test that it all works?
> FLOE-289: Add security screencast and update links to prefs editors screencast.

- index.html
We talked about not actually merging this pull request until the chart authoring tool have been updated a bit, but it could be reviewed in the meantime.
> FLOE-435: Add link to chart authoring tool

- index.html
> FLOE-440: Add a "Recent Events" section to the site

- index.html
Updated Inclusive Design Guidelines link to the GPII version.
> NO-JIRA: updated link

- index.html
This updates the MyL3 link to go to the master index page for Preference Exploration and Self-Assessment.
> NOJIRA: update MyL3 link.

- lib/infusion/VERSION.md
- lib/infusion/infusion-custom.js
- lib/infusion/src/framework/preferences/css/PrefsEditor.css
- lib/infusion/src/framework/preferences/css/SeparatedPanelPrefsEditorFrame.css
- lib/infusion/src/framework/preferences/css/stylus/PrefsEditor.styl
- lib/infusion/src/framework/preferences/css/stylus/SeparatedPanelPrefsEditorFrame.styl
- lib/infusion/src/framework/preferences/messages/contrast.json
https://issues.fluidproject.org/browse/FLUID-5534
> FLUID-5534: Upgrading Infusion to get fixes for FLUID-5534

- news/2017-08-30-self-assessment-toolkit.html
- news/index.html
Fixed a typo and removed white space.
> NO-JIRA: Fixed a typo.

- css/style.css
- js/resources.js
- resources.html
[JIRA](https://issues.fluidproject.org/browse/FLOE-540)
List of links to various resources related to FLOE and Inclusive Design.
> FLOE 540: Create a new Resources page

- css/style.css
- index.html
- news/index.html
- resources.html
Also changed some wording (ILDH) and fixed links.
> FLOE 540: Add navigation to News and Resources

- css/style.css
- js/resources.js
- resources.html
Fixed markup to comply with W3C validation, adjusted spacing and font-sizing for easier readability.
> FLOE-540: Fixed markup for W3C validation

- css/style.css
- js/resources.js
- resources.html
Refactored the jQuery to remove repetition, and changed CSS/markup scoping and renamed class names for easier reading and to make more semantic sense.
> FLOE-540: Did some further refactoring

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-request-or-enhancement.md
Adding issue templates for enhancements and bugs.
> Update issue templates

- js/floe.js
> FLOE-582: Added tocMessage option in fluid.uiOptions.prefsEditor

- src/index.html
Resolves https://issues.fluidproject.org/browse/FLOE-446.
> FLOE-446: update Infusion link to point to Fluid Project site

- .eleventy.js
- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Gruntfile.js
- src/assets/js/floe.js
- src/assets/js/resources.js
- src/index.html
- src/news/2013-03-05-fluid-releases-new-video-player.md
> ci: Update due rename of default branch to main (resolves #202)

- src/404.html
- src/news/2017-08-30-self-assessment-toolkit.md
- src/news/2019-06-28-Code-Learn-Create.md
> fix: resolve netlify-plugin-checklinks errors (resolves #204)

- .github/workflows/ci.yml
Adds CI for linting each pull request.
> feat: add CI

- src/index.html
> chore: removed erroneous bracket in metadata github URL

- src/news/2021-09-07-Infusion-3.0-Release.md
> docs(news): Add article for Infusion 3.0 release (Resolves #228)

- AUTHORS.md
- package.json
- src/assets/styles/app.css
- src/collections/pages/404.md
Updates the 404 page content and styling.
This update also bumps the version number up to 2.1.0 for this change and other "[Phase 2](https://github.com/fluid-project/floeproject.org/projects/3)" changes
1. Go to a page that doesn't exist
**Expected behavior:**
The page text should be
"404 error
Sorry, this page doesn't exist.
Back to home"
N/A
Resolves #263
> feat: update 404 page

- src/collections/news/2023-04-12-BBB-Intro.md
@agamba, could you review this news article. Pinging you here as your github id is not showing up in the reviewers list.
> feat: add a news article about the Baby Bliss Bot project

- eleventy.config.js
- src/collections/news/news.json
> fix: news date url issue (resolves #367)

- src/collections/news/2024-08-24-accessible-interactive-educational-game-design.md
- src/collections/news/2024-10-07-phet-number-pairs-simulation.md
- src/collections/news/2025-01-06-community-led-co-design-with-agriculture-co-operatives.md
- src/collections/news/2025-01-10-data-communities-for-inclusion-case-studies.md
- src/collections/news/2025-05-20-inclusive-standards-hub.md
- src/collections/news/2025-06-16-guidebook-for-financial-inclusion.md
- src/collections/news/2025-07-07-french-language-support-in-weavly.md
Added 7 new news items on this google doc: https://docs.google.com/document/d/1md4WDtayJJI8nsp3h_JnP8BDzflQV70JQ4MvrzU29KQ/edit?usp=sharing
> feat: add 7 new news items
